server:
  port: 31000
spring:
  application:
    name: xc‐service‐manage‐cms‐client
  data:
    mongodb:
      database: xc_cms
      port: 27017
      password: root
      username: root
      host: localhost
  rabbitmq:
    host: 192.168.85.131
    port: 5672
    username: guest
    password: guest
    virtualHost: /
xuecheng:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_03
    routingKey: 609e72e631ed2f50046a3b3e #此routingKey为门户站点ID