server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      database: xc_media
      port: 27017
      host: localhost
  #rabbitmq配置
  rabbitmq:
    host: 192.168.85.131
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: D:/Auserfile/program/xcEduI01/video/
  ffmpeg-path: D:/ffmpeg-20180227-fa0c9d6-win64-static/bin/ffmpeg.exe